version: '3'

networks:
  shared:
   external:
    name: mysql_net

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
    networks:
      - shared


  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
    networks:
      - shared
